SELECT * FROM Customers;
SELECT * FROM Order_items;
SELECT * FROM Orders;
SELECT * FROM Payments;
SELECT * FROM Products;

-- 1. What is the total revenue generated by the business?

SELECT ROUND(SUM(amount)::numeric,2) AS total_revenue
FROM payments;


-- 2. Total Orders
SELECT COUNT(*) AS total_orders
FROM orders;


-- 3. Order Status

SELECT
status,
COUNT(*) AS total_orders
FROM orders
where status != 'Unknown'
GROUP BY status;

-- 4. Payment Method

SELECT
payment_method,
COUNT(*) AS transactions
FROM payments
WHERE payment_method != 'Unknown'
GROUP BY payment_method;

-- 5. Which payment method contributes the most revenue?

SELECT
payment_method,
SUM(amount) AS revenue
FROM payments
WHERE payment_method != 'Unknown'
GROUP BY payment_method
ORDER BY revenue DESC;



-- 6.What is the average transaction value for each payment method?

SELECT
payment_method,
AVG(amount) AS avg_amount
FROM payments
WHERE payment_method != 'Unknown'
GROUP BY payment_method;


-- 7. Which individual orders generated the most revenue?

SELECT
order_id,
SUM(amount) AS revenue
FROM payments
GROUP BY order_id
ORDER BY revenue DESC
LIMIT 10;


-- 8. Revenue by Top 5 Category

SELECT
p.category,
SUM(oi.quantity * oi.unit_price) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
WHERE category != 'Unknown'
GROUP BY p.category
Order by revenue desc;

-- 9. Which brands are the most popular by units sold?

SELECT
p.brand,
SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
WHERE p.brand != 'Unknown'
GROUP BY p.brand
ORDER BY total_quantity DESC;


-- 10. Revenue by City

SELECT
c.city,
SUM(p.amount) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
WHERE city != 'Unknown'
GROUP BY c.city;

-- 11.Customers by City

WITH city_sales AS (
SELECT city,
COUNT(*) AS total_customers
FROM customers
GROUP BY city
)
SELECT *
FROM city_sales
WHERE city != 'Unknown';

-- 12.Which brands contribute the most revenue?

SELECT
p.brand,
SUM(oi.quantity * oi.unit_price) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
WHERE brand != 'Unknown'
GROUP BY p.brand
ORDER BY revenue DESC
LIMIT 5;


-- 13. Which are the top 10 customers by spending?

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(p.amount) AS total_spent
    FROM customers c
    JOIN orders o
    ON c.customer_id = o.customer_id
    JOIN payments p
    ON o.order_id = p.order_id
    GROUP BY c.customer_id, c.customer_name
)

SELECT *
FROM customer_spending
ORDER BY total_spent DESC
LIMIT 10;

-- 14. Rank customers based on their spending.

SELECT
    c.customer_id,
    c.customer_name,
    SUM(p.amount) AS total_spent,
    RANK() OVER(
        ORDER BY SUM(p.amount) DESC
    ) AS customer_rank
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_id, c.customer_name;

-- 15. Rank categories by revenue.

SELECT
    p.category,
    SUM(oi.quantity * oi.unit_price) AS revenue,

    DENSE_RANK() OVER(
        ORDER BY SUM(oi.quantity * oi.unit_price) DESC
    ) AS revenue_rank

FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id

GROUP BY p.category;
